macos_arm64_task:
  name: Build macOS arm64 wheels.
  only_if: $CIRRUS_TAG =~ 'v.*' && $CIRRUS_REPO_OWNER == 'cmake-wheel'
  environment:
    TWINE_PASSWORD: ENCRYPTED[215da7065b4ab96e762bfb2270f9052d321e4bb2f97bcb7b0026da52b692c4ab196b190c20e013e9b986872b1500cd08]
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    CIRRUS_CLONE_SUBMODULES: true
    CMEEL_LOG_LEVEL: DEBUG
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
  install_pre_requirements_script:
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
  install_deps_script:
    - python -m pip install -U pip
    - python -m pip install twine
  run_wheel_script:
    - python -m pip wheel -vw wh .
  publish_script:
    - python -m twine upload -u __token__ wh/cmeel_texinfo*.whl
  wheels_artifacts:
    path: "wh/*"
